// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/transcodev1/transcoder.proto

package transcodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscodeProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VideoCodec    string                 `protobuf:"bytes,3,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"` // "h264", "hevc", "av1"
	AudioCodec    string                 `protobuf:"bytes,4,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"` // "copy", "aac", "opus", "ac3"
	Preset        string                 `protobuf:"bytes,5,opt,name=preset,proto3" json:"preset,omitempty"`                           // "fast", "medium", "slow", "veryslow"
	Crf           int32                  `protobuf:"varint,6,opt,name=crf,proto3" json:"crf,omitempty"`                                // 0-51, lower = better quality
	MaxWidth      int32                  `protobuf:"varint,7,opt,name=max_width,json=maxWidth,proto3" json:"max_width,omitempty"`      // 0 = original
	MaxHeight     int32                  `protobuf:"varint,8,opt,name=max_height,json=maxHeight,proto3" json:"max_height,omitempty"`   // 0 = original
	UseGpu        bool                   `protobuf:"varint,9,opt,name=use_gpu,json=useGpu,proto3" json:"use_gpu,omitempty"`
	Container     string                 `protobuf:"bytes,10,opt,name=container,proto3" json:"container,omitempty"` // "mkv", "mp4"
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeProfile) Reset() {
	*x = TranscodeProfile{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeProfile) ProtoMessage() {}

func (x *TranscodeProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeProfile.ProtoReflect.Descriptor instead.
func (*TranscodeProfile) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{0}
}

func (x *TranscodeProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TranscodeProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TranscodeProfile) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

func (x *TranscodeProfile) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *TranscodeProfile) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *TranscodeProfile) GetCrf() int32 {
	if x != nil {
		return x.Crf
	}
	return 0
}

func (x *TranscodeProfile) GetMaxWidth() int32 {
	if x != nil {
		return x.MaxWidth
	}
	return 0
}

func (x *TranscodeProfile) GetMaxHeight() int32 {
	if x != nil {
		return x.MaxHeight
	}
	return 0
}

func (x *TranscodeProfile) GetUseGpu() bool {
	if x != nil {
		return x.UseGpu
	}
	return false
}

func (x *TranscodeProfile) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *TranscodeProfile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TranscodeProfile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{1}
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*TranscodeProfile    `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{2}
}

func (x *ListProfilesResponse) GetProfiles() []*TranscodeProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type CreateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VideoCodec    string                 `protobuf:"bytes,2,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"`
	AudioCodec    string                 `protobuf:"bytes,3,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"`
	Preset        string                 `protobuf:"bytes,4,opt,name=preset,proto3" json:"preset,omitempty"`
	Crf           int32                  `protobuf:"varint,5,opt,name=crf,proto3" json:"crf,omitempty"`
	MaxWidth      int32                  `protobuf:"varint,6,opt,name=max_width,json=maxWidth,proto3" json:"max_width,omitempty"`
	MaxHeight     int32                  `protobuf:"varint,7,opt,name=max_height,json=maxHeight,proto3" json:"max_height,omitempty"`
	UseGpu        bool                   `protobuf:"varint,8,opt,name=use_gpu,json=useGpu,proto3" json:"use_gpu,omitempty"`
	Container     string                 `protobuf:"bytes,9,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProfileRequest) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

func (x *CreateProfileRequest) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *CreateProfileRequest) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *CreateProfileRequest) GetCrf() int32 {
	if x != nil {
		return x.Crf
	}
	return 0
}

func (x *CreateProfileRequest) GetMaxWidth() int32 {
	if x != nil {
		return x.MaxWidth
	}
	return 0
}

func (x *CreateProfileRequest) GetMaxHeight() int32 {
	if x != nil {
		return x.MaxHeight
	}
	return 0
}

func (x *CreateProfileRequest) GetUseGpu() bool {
	if x != nil {
		return x.UseGpu
	}
	return false
}

func (x *CreateProfileRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type CreateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *TranscodeProfile      `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProfileResponse) GetProfile() *TranscodeProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VideoCodec    string                 `protobuf:"bytes,3,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"`
	AudioCodec    string                 `protobuf:"bytes,4,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"`
	Preset        string                 `protobuf:"bytes,5,opt,name=preset,proto3" json:"preset,omitempty"`
	Crf           int32                  `protobuf:"varint,6,opt,name=crf,proto3" json:"crf,omitempty"`
	MaxWidth      int32                  `protobuf:"varint,7,opt,name=max_width,json=maxWidth,proto3" json:"max_width,omitempty"`
	MaxHeight     int32                  `protobuf:"varint,8,opt,name=max_height,json=maxHeight,proto3" json:"max_height,omitempty"`
	UseGpu        bool                   `protobuf:"varint,9,opt,name=use_gpu,json=useGpu,proto3" json:"use_gpu,omitempty"`
	Container     string                 `protobuf:"bytes,10,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileRequest) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

func (x *UpdateProfileRequest) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *UpdateProfileRequest) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *UpdateProfileRequest) GetCrf() int32 {
	if x != nil {
		return x.Crf
	}
	return 0
}

func (x *UpdateProfileRequest) GetMaxWidth() int32 {
	if x != nil {
		return x.MaxWidth
	}
	return 0
}

func (x *UpdateProfileRequest) GetMaxHeight() int32 {
	if x != nil {
		return x.MaxHeight
	}
	return 0
}

func (x *UpdateProfileRequest) GetUseGpu() bool {
	if x != nil {
		return x.UseGpu
	}
	return false
}

func (x *UpdateProfileRequest) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *TranscodeProfile      `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProfileResponse) GetProfile() *TranscodeProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type DeleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileRequest) Reset() {
	*x = DeleteProfileRequest{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileRequest) ProtoMessage() {}

func (x *DeleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileRequest.ProtoReflect.Descriptor instead.
func (*DeleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProfileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProfileResponse) Reset() {
	*x = DeleteProfileResponse{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProfileResponse) ProtoMessage() {}

func (x *DeleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProfileResponse.ProtoReflect.Descriptor instead.
func (*DeleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{8}
}

type EnqueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputPath     string                 `protobuf:"bytes,1,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	OutputPath    string                 `protobuf:"bytes,2,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	ProfileId     string                 `protobuf:"bytes,3,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{9}
}

func (x *EnqueueRequest) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *EnqueueRequest) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *EnqueueRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{10}
}

func (x *EnqueueResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{11}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{12}
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "all", "queued", "running", "completed", "failed", "cancelled"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{13}
}

func (x *ListJobsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListJobsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*TranscodeJob        `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{14}
}

func (x *ListJobsResponse) GetJobs() []*TranscodeJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListJobsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListJobsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{15}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *TranscodeJob          `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{16}
}

func (x *GetJobResponse) GetJob() *TranscodeJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type TranscodeJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InputPath     string                 `protobuf:"bytes,2,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	OutputPath    string                 `protobuf:"bytes,3,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	ProfileId     string                 `protobuf:"bytes,4,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	ProfileName   string                 `protobuf:"bytes,5,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`       // "queued", "running", "completed", "failed", "cancelled"
	Progress      float64                `protobuf:"fixed64,7,opt,name=progress,proto3" json:"progress,omitempty"` // 0.0 - 1.0
	Fps           float64                `protobuf:"fixed64,8,opt,name=fps,proto3" json:"fps,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt     string                 `protobuf:"bytes,10,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,11,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeJob) Reset() {
	*x = TranscodeJob{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeJob) ProtoMessage() {}

func (x *TranscodeJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeJob.ProtoReflect.Descriptor instead.
func (*TranscodeJob) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{17}
}

func (x *TranscodeJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TranscodeJob) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *TranscodeJob) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *TranscodeJob) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *TranscodeJob) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *TranscodeJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TranscodeJob) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TranscodeJob) GetFps() float64 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *TranscodeJob) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TranscodeJob) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *TranscodeJob) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *TranscodeJob) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TranscodeJob) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DetectHardwareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectHardwareRequest) Reset() {
	*x = DetectHardwareRequest{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectHardwareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectHardwareRequest) ProtoMessage() {}

func (x *DetectHardwareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectHardwareRequest.ProtoReflect.Descriptor instead.
func (*DetectHardwareRequest) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{18}
}

type DetectHardwareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*HardwareDevice      `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectHardwareResponse) Reset() {
	*x = DetectHardwareResponse{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectHardwareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectHardwareResponse) ProtoMessage() {}

func (x *DetectHardwareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectHardwareResponse.ProtoReflect.Descriptor instead.
func (*DetectHardwareResponse) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{19}
}

func (x *DetectHardwareResponse) GetDevices() []*HardwareDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type HardwareDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "nvenc", "vaapi", "qsv", "videotoolbox"
	Available     bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Encoder       string                 `protobuf:"bytes,4,opt,name=encoder,proto3" json:"encoder,omitempty"` // "h264_nvenc", "hevc_nvenc", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardwareDevice) Reset() {
	*x = HardwareDevice{}
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardwareDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardwareDevice) ProtoMessage() {}

func (x *HardwareDevice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transcodev1_transcoder_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardwareDevice.ProtoReflect.Descriptor instead.
func (*HardwareDevice) Descriptor() ([]byte, []int) {
	return file_proto_transcodev1_transcoder_proto_rawDescGZIP(), []int{20}
}

func (x *HardwareDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HardwareDevice) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HardwareDevice) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *HardwareDevice) GetEncoder() string {
	if x != nil {
		return x.Encoder
	}
	return ""
}

var File_proto_transcodev1_transcoder_proto protoreflect.FileDescriptor

const file_proto_transcodev1_transcoder_proto_rawDesc = "" +
	"\n" +
	"\"proto/transcodev1/transcoder.proto\x12\x15muxcore.transcoder.v1\"\xd3\x02\n" +
	"\x10TranscodeProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vvideo_codec\x18\x03 \x01(\tR\n" +
	"videoCodec\x12\x1f\n" +
	"\vaudio_codec\x18\x04 \x01(\tR\n" +
	"audioCodec\x12\x16\n" +
	"\x06preset\x18\x05 \x01(\tR\x06preset\x12\x10\n" +
	"\x03crf\x18\x06 \x01(\x05R\x03crf\x12\x1b\n" +
	"\tmax_width\x18\a \x01(\x05R\bmaxWidth\x12\x1d\n" +
	"\n" +
	"max_height\x18\b \x01(\x05R\tmaxHeight\x12\x17\n" +
	"\ause_gpu\x18\t \x01(\bR\x06useGpu\x12\x1c\n" +
	"\tcontainer\x18\n" +
	" \x01(\tR\tcontainer\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\x15\n" +
	"\x13ListProfilesRequest\"[\n" +
	"\x14ListProfilesResponse\x12C\n" +
	"\bprofiles\x18\x01 \x03(\v2'.muxcore.transcoder.v1.TranscodeProfileR\bprofiles\"\x89\x02\n" +
	"\x14CreateProfileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vvideo_codec\x18\x02 \x01(\tR\n" +
	"videoCodec\x12\x1f\n" +
	"\vaudio_codec\x18\x03 \x01(\tR\n" +
	"audioCodec\x12\x16\n" +
	"\x06preset\x18\x04 \x01(\tR\x06preset\x12\x10\n" +
	"\x03crf\x18\x05 \x01(\x05R\x03crf\x12\x1b\n" +
	"\tmax_width\x18\x06 \x01(\x05R\bmaxWidth\x12\x1d\n" +
	"\n" +
	"max_height\x18\a \x01(\x05R\tmaxHeight\x12\x17\n" +
	"\ause_gpu\x18\b \x01(\bR\x06useGpu\x12\x1c\n" +
	"\tcontainer\x18\t \x01(\tR\tcontainer\"Z\n" +
	"\x15CreateProfileResponse\x12A\n" +
	"\aprofile\x18\x01 \x01(\v2'.muxcore.transcoder.v1.TranscodeProfileR\aprofile\"\x99\x02\n" +
	"\x14UpdateProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vvideo_codec\x18\x03 \x01(\tR\n" +
	"videoCodec\x12\x1f\n" +
	"\vaudio_codec\x18\x04 \x01(\tR\n" +
	"audioCodec\x12\x16\n" +
	"\x06preset\x18\x05 \x01(\tR\x06preset\x12\x10\n" +
	"\x03crf\x18\x06 \x01(\x05R\x03crf\x12\x1b\n" +
	"\tmax_width\x18\a \x01(\x05R\bmaxWidth\x12\x1d\n" +
	"\n" +
	"max_height\x18\b \x01(\x05R\tmaxHeight\x12\x17\n" +
	"\ause_gpu\x18\t \x01(\bR\x06useGpu\x12\x1c\n" +
	"\tcontainer\x18\n" +
	" \x01(\tR\tcontainer\"Z\n" +
	"\x15UpdateProfileResponse\x12A\n" +
	"\aprofile\x18\x01 \x01(\v2'.muxcore.transcoder.v1.TranscodeProfileR\aprofile\"&\n" +
	"\x14DeleteProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteProfileResponse\"o\n" +
	"\x0eEnqueueRequest\x12\x1d\n" +
	"\n" +
	"input_path\x18\x01 \x01(\tR\tinputPath\x12\x1f\n" +
	"\voutput_path\x18\x02 \x01(\tR\n" +
	"outputPath\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tR\tprofileId\"(\n" +
	"\x0fEnqueueResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x13\n" +
	"\x11CancelJobResponse\"Z\n" +
	"\x0fListJobsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x92\x01\n" +
	"\x10ListJobsResponse\x127\n" +
	"\x04jobs\x18\x01 \x03(\v2#.muxcore.transcoder.v1.TranscodeJobR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"G\n" +
	"\x0eGetJobResponse\x125\n" +
	"\x03job\x18\x01 \x01(\v2#.muxcore.transcoder.v1.TranscodeJobR\x03job\"\xfc\x02\n" +
	"\fTranscodeJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"input_path\x18\x02 \x01(\tR\tinputPath\x12\x1f\n" +
	"\voutput_path\x18\x03 \x01(\tR\n" +
	"outputPath\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x04 \x01(\tR\tprofileId\x12!\n" +
	"\fprofile_name\x18\x05 \x01(\tR\vprofileName\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\a \x01(\x01R\bprogress\x12\x10\n" +
	"\x03fps\x18\b \x01(\x01R\x03fps\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"started_at\x18\n" +
	" \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\v \x01(\tR\vcompletedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\"\x17\n" +
	"\x15DetectHardwareRequest\"Y\n" +
	"\x16DetectHardwareResponse\x12?\n" +
	"\adevices\x18\x01 \x03(\v2%.muxcore.transcoder.v1.HardwareDeviceR\adevices\"p\n" +
	"\x0eHardwareDevice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\x12\x18\n" +
	"\aencoder\x18\x04 \x01(\tR\aencoder2\x9c\a\n" +
	"\x10TranscodeService\x12g\n" +
	"\fListProfiles\x12*.muxcore.transcoder.v1.ListProfilesRequest\x1a+.muxcore.transcoder.v1.ListProfilesResponse\x12j\n" +
	"\rCreateProfile\x12+.muxcore.transcoder.v1.CreateProfileRequest\x1a,.muxcore.transcoder.v1.CreateProfileResponse\x12j\n" +
	"\rUpdateProfile\x12+.muxcore.transcoder.v1.UpdateProfileRequest\x1a,.muxcore.transcoder.v1.UpdateProfileResponse\x12j\n" +
	"\rDeleteProfile\x12+.muxcore.transcoder.v1.DeleteProfileRequest\x1a,.muxcore.transcoder.v1.DeleteProfileResponse\x12X\n" +
	"\aEnqueue\x12%.muxcore.transcoder.v1.EnqueueRequest\x1a&.muxcore.transcoder.v1.EnqueueResponse\x12^\n" +
	"\tCancelJob\x12'.muxcore.transcoder.v1.CancelJobRequest\x1a(.muxcore.transcoder.v1.CancelJobResponse\x12[\n" +
	"\bListJobs\x12&.muxcore.transcoder.v1.ListJobsRequest\x1a'.muxcore.transcoder.v1.ListJobsResponse\x12U\n" +
	"\x06GetJob\x12$.muxcore.transcoder.v1.GetJobRequest\x1a%.muxcore.transcoder.v1.GetJobResponse\x12m\n" +
	"\x0eDetectHardware\x12,.muxcore.transcoder.v1.DetectHardwareRequest\x1a-.muxcore.transcoder.v1.DetectHardwareResponseBIZGgithub.com/Muxcore-Media/media-transcoder/proto/transcodev1;transcodev1b\x06proto3"

var (
	file_proto_transcodev1_transcoder_proto_rawDescOnce sync.Once
	file_proto_transcodev1_transcoder_proto_rawDescData []byte
)

func file_proto_transcodev1_transcoder_proto_rawDescGZIP() []byte {
	file_proto_transcodev1_transcoder_proto_rawDescOnce.Do(func() {
		file_proto_transcodev1_transcoder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transcodev1_transcoder_proto_rawDesc), len(file_proto_transcodev1_transcoder_proto_rawDesc)))
	})
	return file_proto_transcodev1_transcoder_proto_rawDescData
}

var file_proto_transcodev1_transcoder_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_transcodev1_transcoder_proto_goTypes = []any{
	(*TranscodeProfile)(nil),       // 0: muxcore.transcoder.v1.TranscodeProfile
	(*ListProfilesRequest)(nil),    // 1: muxcore.transcoder.v1.ListProfilesRequest
	(*ListProfilesResponse)(nil),   // 2: muxcore.transcoder.v1.ListProfilesResponse
	(*CreateProfileRequest)(nil),   // 3: muxcore.transcoder.v1.CreateProfileRequest
	(*CreateProfileResponse)(nil),  // 4: muxcore.transcoder.v1.CreateProfileResponse
	(*UpdateProfileRequest)(nil),   // 5: muxcore.transcoder.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),  // 6: muxcore.transcoder.v1.UpdateProfileResponse
	(*DeleteProfileRequest)(nil),   // 7: muxcore.transcoder.v1.DeleteProfileRequest
	(*DeleteProfileResponse)(nil),  // 8: muxcore.transcoder.v1.DeleteProfileResponse
	(*EnqueueRequest)(nil),         // 9: muxcore.transcoder.v1.EnqueueRequest
	(*EnqueueResponse)(nil),        // 10: muxcore.transcoder.v1.EnqueueResponse
	(*CancelJobRequest)(nil),       // 11: muxcore.transcoder.v1.CancelJobRequest
	(*CancelJobResponse)(nil),      // 12: muxcore.transcoder.v1.CancelJobResponse
	(*ListJobsRequest)(nil),        // 13: muxcore.transcoder.v1.ListJobsRequest
	(*ListJobsResponse)(nil),       // 14: muxcore.transcoder.v1.ListJobsResponse
	(*GetJobRequest)(nil),          // 15: muxcore.transcoder.v1.GetJobRequest
	(*GetJobResponse)(nil),         // 16: muxcore.transcoder.v1.GetJobResponse
	(*TranscodeJob)(nil),           // 17: muxcore.transcoder.v1.TranscodeJob
	(*DetectHardwareRequest)(nil),  // 18: muxcore.transcoder.v1.DetectHardwareRequest
	(*DetectHardwareResponse)(nil), // 19: muxcore.transcoder.v1.DetectHardwareResponse
	(*HardwareDevice)(nil),         // 20: muxcore.transcoder.v1.HardwareDevice
}
var file_proto_transcodev1_transcoder_proto_depIdxs = []int32{
	0,  // 0: muxcore.transcoder.v1.ListProfilesResponse.profiles:type_name -> muxcore.transcoder.v1.TranscodeProfile
	0,  // 1: muxcore.transcoder.v1.CreateProfileResponse.profile:type_name -> muxcore.transcoder.v1.TranscodeProfile
	0,  // 2: muxcore.transcoder.v1.UpdateProfileResponse.profile:type_name -> muxcore.transcoder.v1.TranscodeProfile
	17, // 3: muxcore.transcoder.v1.ListJobsResponse.jobs:type_name -> muxcore.transcoder.v1.TranscodeJob
	17, // 4: muxcore.transcoder.v1.GetJobResponse.job:type_name -> muxcore.transcoder.v1.TranscodeJob
	20, // 5: muxcore.transcoder.v1.DetectHardwareResponse.devices:type_name -> muxcore.transcoder.v1.HardwareDevice
	1,  // 6: muxcore.transcoder.v1.TranscodeService.ListProfiles:input_type -> muxcore.transcoder.v1.ListProfilesRequest
	3,  // 7: muxcore.transcoder.v1.TranscodeService.CreateProfile:input_type -> muxcore.transcoder.v1.CreateProfileRequest
	5,  // 8: muxcore.transcoder.v1.TranscodeService.UpdateProfile:input_type -> muxcore.transcoder.v1.UpdateProfileRequest
	7,  // 9: muxcore.transcoder.v1.TranscodeService.DeleteProfile:input_type -> muxcore.transcoder.v1.DeleteProfileRequest
	9,  // 10: muxcore.transcoder.v1.TranscodeService.Enqueue:input_type -> muxcore.transcoder.v1.EnqueueRequest
	11, // 11: muxcore.transcoder.v1.TranscodeService.CancelJob:input_type -> muxcore.transcoder.v1.CancelJobRequest
	13, // 12: muxcore.transcoder.v1.TranscodeService.ListJobs:input_type -> muxcore.transcoder.v1.ListJobsRequest
	15, // 13: muxcore.transcoder.v1.TranscodeService.GetJob:input_type -> muxcore.transcoder.v1.GetJobRequest
	18, // 14: muxcore.transcoder.v1.TranscodeService.DetectHardware:input_type -> muxcore.transcoder.v1.DetectHardwareRequest
	2,  // 15: muxcore.transcoder.v1.TranscodeService.ListProfiles:output_type -> muxcore.transcoder.v1.ListProfilesResponse
	4,  // 16: muxcore.transcoder.v1.TranscodeService.CreateProfile:output_type -> muxcore.transcoder.v1.CreateProfileResponse
	6,  // 17: muxcore.transcoder.v1.TranscodeService.UpdateProfile:output_type -> muxcore.transcoder.v1.UpdateProfileResponse
	8,  // 18: muxcore.transcoder.v1.TranscodeService.DeleteProfile:output_type -> muxcore.transcoder.v1.DeleteProfileResponse
	10, // 19: muxcore.transcoder.v1.TranscodeService.Enqueue:output_type -> muxcore.transcoder.v1.EnqueueResponse
	12, // 20: muxcore.transcoder.v1.TranscodeService.CancelJob:output_type -> muxcore.transcoder.v1.CancelJobResponse
	14, // 21: muxcore.transcoder.v1.TranscodeService.ListJobs:output_type -> muxcore.transcoder.v1.ListJobsResponse
	16, // 22: muxcore.transcoder.v1.TranscodeService.GetJob:output_type -> muxcore.transcoder.v1.GetJobResponse
	19, // 23: muxcore.transcoder.v1.TranscodeService.DetectHardware:output_type -> muxcore.transcoder.v1.DetectHardwareResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_transcodev1_transcoder_proto_init() }
func file_proto_transcodev1_transcoder_proto_init() {
	if File_proto_transcodev1_transcoder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transcodev1_transcoder_proto_rawDesc), len(file_proto_transcodev1_transcoder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transcodev1_transcoder_proto_goTypes,
		DependencyIndexes: file_proto_transcodev1_transcoder_proto_depIdxs,
		MessageInfos:      file_proto_transcodev1_transcoder_proto_msgTypes,
	}.Build()
	File_proto_transcodev1_transcoder_proto = out.File
	file_proto_transcodev1_transcoder_proto_goTypes = nil
	file_proto_transcodev1_transcoder_proto_depIdxs = nil
}
